
create table COMMENT(
                        ID             bigint generated by default as identity,
                        post_id           bigint Not NULL,
                        comment_name      VARCHAR(50) NOT NULL COMMENT '댓글작성자',
                        comment_password      VARCHAR(255) NOT NULL COMMENT '댓글비밀번호',
                        comment_content       TEXT NOT NULL COMMENT '댓글내용',
                        created_at      DATETIME NOT NULL COMMENT '작성일자',
                        updated_at      DATETIME DEFAULT NULL COMMENT '수정일자'
);
alter table COMMENT add constraint post_id foreign key (post_id) references POST(id);

ALTER table COMMENT drop COLUMN POST;
ALTER table COMMENT drop COLUMN COMMENTS;