create table POST(
                     ID             bigint generated by default as identity,
                     post_name      VARCHAR(50) NOT NULL COMMENT '작성자',
                     post_password      VARCHAR(255) NOT NULL COMMENT '비밀번호',
                     post_content       TEXT NOT NULL COMMENT '내용',
                     created_at      DATETIME NOT NULL COMMENT '작성시간',
                     updated_at      DATETIME DEFAULT NULL COMMENT '수정시간',
                     primary key (id)
);

-- 댓글 개수
SELECT id, post_name, post_content, updated_at,
       (SELECT COUNT(*) AS cnt FROM COMMENT WHERE comment.post_id = POST.id) as CommentTotalCnt
FROM POST
